//
//  TMDb.swift
//  TMDb
//
//  Created by Shane Whitehead on 22/9/17.
//  Copyright © 2017 TMDb. All rights reserved.
//

import Foundation

/*
v3 API Key: ...
API Read Access Token (v4): ...
example: https://api.themoviedb.org/3/movie/550?api_key=...
*/

let baseURL = "https://api.themoviedb.org/3"

public protocol Identifiable {
  var id: Int {get}
}

public class TMDb {
  public static var shared: TMDb = TMDb()
  
  public var apiKey: String?
  public var readAccessToken: String?
  
  fileprivate init() {
  }
}

/*
 Language + Country
 english + australia = en-AU
 */

public enum Country: String {
  Afghanistan" = "AF"
  Ã…land Islands" = "AX"
  Albania" = "AL"
  Algeria" = "DZ"
  American Samoa" = "AS"
  Andorra" = "AD"
  Angola" = "AO"
  Anguilla" = "AI"
  Antarctica" = "AQ"
  Antigua and Barbuda" = "AG"
  Argentina" = "AR"
  Armenia" = "AM"
  Aruba" = "AW"
  Australia" = "AU"
  Austria" = "AT"
  Azerbaijan" = "AZ"
  Bahamas" = "BS"
  Bahrain" = "BH"
  Bangladesh" = "BD"
  Barbados" = "BB"
  Belarus" = "BY"
  Belgium" = "BE"
  Belize" = "BZ"
  Benin" = "BJ"
  Bermuda" = "BM"
  Bhutan" = "BT"
  "Bolivia" = " Plurinational State of"" = "BO"
  "Bonaire" = " Sint Eustatius and Saba"" = "BQ"
  Bosnia and Herzegovina" = "BA"
  Botswana" = "BW"
  Bouvet Island" = "BV"
  Brazil" = "BR"
  British Indian Ocean Territory" = "IO"
  Brunei Darussalam" = "BN"
  Bulgaria" = "BG"
  Burkina Faso" = "BF"
  Burundi" = "BI"
  Cambodia" = "KH"
  Cameroon" = "CM"
  Canada" = "CA"
  Cape Verde" = "CV"
  Cayman Islands" = "KY"
  Central African Republic" = "CF"
  Chad" = "TD"
  Chile" = "CL"
  China" = "CN"
  Christmas Island" = "CX"
  Cocos (Keeling) Islands" = "CC"
  Colombia" = "CO"
  Comoros" = "KM"
  Congo" = "CG"
  "Congo" = " the Democratic Republic of the"" = "CD"
  Cook Islands" = "CK"
  Costa Rica" = "CR"
  CÃ´te d'Ivoire" = "CI"
  Croatia" = "HR"
  Cuba" = "CU"
  CuraÃ§ao" = "CW"
  Cyprus" = "CY"
  Czech Republic" = "CZ"
  Denmark" = "DK"
  Djibouti" = "DJ"
  Dominica" = "DM"
  Dominican Republic" = "DO"
  Ecuador" = "EC"
  Egypt" = "EG"
  El Salvador" = "SV"
  Equatorial Guinea" = "GQ"
  Eritrea" = "ER"
  Estonia" = "EE"
  Ethiopia" = "ET"
  Falkland Islands (Malvinas)" = "FK"
  Faroe Islands" = "FO"
  Fiji" = "FJ"
  Finland" = "FI"
  France" = "FR"
  French Guiana" = "GF"
  French Polynesia" = "PF"
  French Southern Territories" = "TF"
  Gabon" = "GA"
  Gambia" = "GM"
  Georgia" = "GE"
  Germany" = "DE"
  Ghana" = "GH"
  Gibraltar" = "GI"
  Greece" = "GR"
  Greenland" = "GL"
  Grenada" = "GD"
  Guadeloupe" = "GP"
  Guam" = "GU"
  Guatemala" = "GT"
  Guernsey" = "GG"
  Guinea" = "GN"
  Guinea-Bissau" = "GW"
  Guyana" = "GY"
  Haiti" = "HT"
  Heard Island and McDonald Islands" = "HM"
  Holy See (Vatican City State)" = "VA"
  Honduras" = "HN"
  Hong Kong" = "HK"
  Hungary" = "HU"
  Iceland" = "IS"
  India" = "IN"
  Indonesia" = "ID"
  "Iran" = " Islamic Republic of"" = "IR"
  Iraq" = "IQ"
  Ireland" = "IE"
  Isle of Man" = "IM"
  Israel" = "IL"
  Italy" = "IT"
  Jamaica" = "JM"
  Japan" = "JP"
  Jersey" = "JE"
  Jordan" = "JO"
  Kazakhstan" = "KZ"
  Kenya" = "KE"
  Kiribati" = "KI"
  "Korea" = " Democratic People's Republic of"" = "KP"
  "Korea" = " Republic of"" = "KR"
  Kuwait" = "KW"
  Kyrgyzstan" = "KG"
  Lao People's Democratic Republic" = "LA"
  Latvia" = "LV"
  Lebanon" = "LB"
  Lesotho" = "LS"
  Liberia" = "LR"
  Libya" = "LY"
  Liechtenstein" = "LI"
  Lithuania" = "LT"
  Luxembourg" = "LU"
  Macao" = "MO"
  "Macedonia" = " the Former Yugoslav Republic of"" = "MK"
  Madagascar" = "MG"
  Malawi" = "MW"
  Malaysia" = "MY"
  Maldives" = "MV"
  Mali" = "ML"
  Malta" = "MT"
  Marshall Islands" = "MH"
  Martinique" = "MQ"
  Mauritania" = "MR"
  Mauritius" = "MU"
  Mayotte" = "YT"
  Mexico" = "MX"
  "Micronesia" = " Federated States of"" = "FM"
  "Moldova" = " Republic of"" = "MD"
  Monaco" = "MC"
  Mongolia" = "MN"
  Montenegro" = "ME"
  Montserrat" = "MS"
  Morocco" = "MA"
  Mozambique" = "MZ"
  Myanmar" = "MM"
  Namibia" = "NA"
  Nauru" = "NR"
  Nepal" = "NP"
  Netherlands" = "NL"
  New Caledonia" = "NC"
  New Zealand" = "NZ"
  Nicaragua" = "NI"
  Niger" = "NE"
  Nigeria" = "NG"
  Niue" = "NU"
  Norfolk Island" = "NF"
  Northern Mariana Islands" = "MP"
  Norway" = "NO"
  Oman" = "OM"
  Pakistan" = "PK"
  Palau" = "PW"
  "Palestine" = " State of"" = "PS"
  Panama" = "PA"
  Papua New Guinea" = "PG"
  Paraguay" = "PY"
  Peru" = "PE"
  Philippines" = "PH"
  Pitcairn" = "PN"
  Poland" = "PL"
  Portugal" = "PT"
  Puerto Rico" = "PR"
  Qatar" = "QA"
  RÃ©union" = "RE"
  Romania" = "RO"
  Russian Federation" = "RU"
  Rwanda" = "RW"
  Saint BarthÃ©lemy" = "BL"
  "Saint Helena" = " Ascension and Tristan da Cunha"" = "SH"
  Saint Kitts and Nevis" = "KN"
  Saint Lucia" = "LC"
  Saint Martin (French part)" = "MF"
  Saint Pierre and Miquelon" = "PM"
  Saint Vincent and the Grenadines" = "VC"
  Samoa" = "WS"
  San Marino" = "SM"
  Sao Tome and Principe" = "ST"
  Saudi Arabia" = "SA"
  Senegal" = "SN"
  Serbia" = "RS"
  Seychelles" = "SC"
  Sierra Leone" = "SL"
  Singapore" = "SG"
  Sint Maarten (Dutch part)" = "SX"
  Slovakia" = "SK"
  Slovenia" = "SI"
  Solomon Islands" = "SB"
  Somalia" = "SO"
  South Africa" = "ZA"
  South Georgia and the South Sandwich Islands" = "GS"
  South Sudan" = "SS"
  Spain" = "ES"
  Sri Lanka" = "LK"
  Sudan" = "SD"
  Suriname" = "SR"
  Svalbard and Jan Mayen" = "SJ"
  Swaziland" = "SZ"
  Sweden" = "SE"
  Switzerland" = "CH"
  Syrian Arab Republic" = "SY"
  "Taiwan" = " Province of China"" = "TW"
  Tajikistan" = "TJ"
  "Tanzania" = " United Republic of"" = "TZ"
  Thailand" = "TH"
  Timor-Leste" = "TL"
  Togo" = "TG"
  Tokelau" = "TK"
  Tonga" = "TO"
  Trinidad and Tobago" = "TT"
  Tunisia" = "TN"
  Turkey" = "TR"
  Turkmenistan" = "TM"
  Turks and Caicos Islands" = "TC"
  Tuvalu" = "TV"
  Uganda" = "UG"
  Ukraine" = "UA"
  United Arab Emirates" = "AE"
  United Kingdom" = "GB"
  United States" = "US"
  United States Minor Outlying Islands" = "UM"
  Uruguay" = "UY"
  Uzbekistan" = "UZ"
  Vanuatu" = "VU"
  "Venezuela" = " Bolivarian Republic of"" = "VE"
  Viet Nam" = "VN"
  "Virgin Islands" = " British"" = "VG"
  "Virgin Islands" = " U.S."" = "VI"
  Wallis and Futuna" = "WF"
  Western Sahara" = "EH"
  Yemen" = "YE"
  Zambia" = "ZM"
  Zimbabwe" = "ZW"
  
}

public struct Language: CustomStringConvertible {
  public let code: String
  private var country: Country?
  
  public init(code: String, country: Country? = nil) {
    self.code = code
    self.country = country
  }
  
  public func from(_ country: Country) -> Language {
    return Language(code: code, country: country)
  }
  
  public var description: String {
    guard let country = country else {
      return code
    }
    
    return "\(code)-\(country.rawValue.uppercased())"
  }
  
}

public extension Language {

  public static let english: Language = Language(code: "en")

}

//public enum Lanuage: String { // ISO-639-1
//  case oromo = "om"
//  case abkhazian = "ab"
//  case afar = "aa"
//  case afrikaans = "af"
//  case albanian = "sq"
//  case amharic = "am"
//  case arabic = "ar"
//  case armenian = "hy"
//  case assamese = "as"
//  case aymara = "ay"
//  case azerbaijani = "az"
//  case bashkir = "ba"
//  case basque = "eu"
//  case bengali = "bn"
//  case bhutani = "dz"
//  case bihari = "bh"
//  case bislama = "bi"
//  case breton = "br"
//  case bulgarian = "bg"
//  case burmese = "my"
//  case byelorussian = "be"
//  case cambodian = "km"
//  case catalan = "ca"
//  case chinese = "zh"
//  case corsican = "co"
//  case croatian = "hr"
//  case czech = "cs"
//  case danish = "da"
//  case dutch = "nl"
//  case english = "en"
//  case esperanto = "eo"
//  case estonian = "et"
//  case faeroese = "fo"
//  case fiji = "fj"
//  case finnish = "fi"
//  case french = "fr"
//  case frisian = "fy"
//  case galician = "gl"
//  case georgian = "ka"
//  case german = "de"
//  case greek = "el"
//  case greenlandic = "kl"
//  case guarani = "gn"
//  case gujarati = "gu"
//  case hausa = "ha"
//  case hebrew = "he"
//  case hindi = "hi"
//  case hungarian = "hu"
//  case icelandic = "is"
//  case indonesian = "id"
//  case interlingua = "ia"
//  case interlingue = "ie"
//  case inupiak = "ik"
//  case inuktitut = "iu"
//  case irish = "ga"
//  case italian = "it"
//  case japanese = "ja"
//  case javanese = "jw"
//  case kannada = "kn"
//  case kashmiri = "ks"
//  case kazakh = "kk"
//  case kinyarwanda = "rw"
//  case kirghiz = "ky"
//  case kirundi = "rn"
//  case korean = "ko"
//  case kurdish = "ku"
//  case laothian = "lo"
//  case latin = "la"
//  case latvian, lettish = "lv"
//  case lingala = "ln"
//  case lithuanian = "lt"
//  case macedonian = "mk"
//  case malagasy = "mg"
//  case malay = "ms"
//  case malayalam = "ml"
//  case maltese = "mt"
//  case maori = "mi"
//  case marathi = "mr"
//  case moldavian = "mo"
//  case mongolian = "mn"
//  case nauru = "na"
//  case nepali = "ne"
//  case norwegian = "no"
//  case occitan = "oc"
//  case oriya = "or"
//  case pashto, pushto = "ps"
//  case persian = "fa"
//  case polish = "pl"
//  case portuguese = "pt"
//  case punjabi = "pa"
//  case quechua = "qu"
//  case rhaetoRomance = "rm"
//  case romanian = "ro"
//  case russian = "ru"
//  case samoan = "sm"
//  case sangro = "sg"
//  case sanskrit = "sa"
//  case scotsGaelic = "gd"
//  case serbian = "sr"
//  case serboCroatian = "sh"
//  case sesotho = "st"
//  case setswana = "tn"
//  case shona = "sn"
//  case sindhi = "sd"
//  case singhalese = "si"
//  case siswati = "ss"
//  case slovak = "sk"
//  case slovenian = "sl"
//  case somali = "so"
//  case spanish = "es"
//  case sudanese = "su"
//  case swahili = "sw"
//  case swedish = "sv"
//  case tagalog = "tl"
//  case tajik = "tg"
//  case tamil = "ta"
//  case tatar = "tt"
//  case tegulu = "te"
//  case thai = "th"
//  case tibetan = "bo"
//  case tigrinya = "ti"
//  case tonga = "to"
//  case tsonga = "ts"
//  case turkish = "tr"
//  case turkmen = "tk"
//  case twi = "tw"
//  case uigur = "ug"
//  case ukrainian = "uk"
//  case urdu = "ur"
//  case uzbek = "uz"
//  case vietnamese = "vi"
//  case volapuk = "vo"
//  case welch = "cy"
//  case wolof = "wo"
//  case xhosa = "xh"
//  case yiddish = "yi"
//  case yoruba = "yo"
//  case zhuang = "za"
//  case zulu = "zu"
//}

